-- Keyword tambahan (Indonesia-wide, tema pinjaman/call center)
INSERT IGNORE INTO keywords (keyword, category) VALUES
('call center easycash', 'call center'),
('nomor telepon easycash', 'call center'),
('call center kredit pintar', 'call center'),
('nomor telepon kredit pintar', 'call center'),
('call center kredivo', 'call center'),
('nomor telepon kredivo', 'call center'),
('call center akulaku', 'call center'),
('nomor telepon akulaku', 'call center'),
('call center rupiah cepat', 'call center'),
('nomor telepon rupiah cepat', 'call center'),
('call center dana tunai', 'call center'),
('nomor telepon dana tunai', 'call center'),
('call center pinjamlah', 'call center'),
('nomor telepon pinjamlah', 'call center'),
('call center uang me', 'call center'),
('nomor telepon uang me', 'call center'),
('call center kta kilat', 'call center'),
('nomor telepon kta kilat', 'call center'),
('call center modalku', 'call center'),
('nomor telepon modalku', 'call center'),
('call center investree', 'call center'),
('nomor telepon investree', 'call center'),
('call center danamon', 'call center'),
('nomor telepon danamon', 'call center'),
('call center bank jago', 'call center'),
('nomor telepon bank jago', 'call center'),
('call center jenius', 'call center'),
('nomor telepon jenius', 'call center'),
('call center blibli', 'call center'),
('nomor telepon blibli', 'call center'),
('call center home credit', 'call center'),
('nomor telepon home credit', 'call center'),
('call center adira', 'call center'),
('nomor telepon adira', 'call center'),
('call center fif group', 'call center'),
('nomor telepon fif group', 'call center'),
('call center women moolah', 'call center'),
('nomor telepon women moolah', 'call center'),
('call center tunas credit', 'call center'),
('nomor telepon tunas credit', 'call center'),
('call center bca finance', 'call center'),
('nomor telepon bca finance', 'call center'),
('call center mega finance', 'call center'),
('nomor telepon mega finance', 'call center'),
('call center mandiri utama', 'call center'),
('nomor telepon mandiri utama', 'call center'),
('call center utoledo', 'call center'),
('nomor telepon utoledo', 'call center'),
('call center jutawan', 'call center'),
('nomor telepon jutawan', 'call center'),
('call center mau cash', 'call center'),
('nomor telepon mau cash', 'call center'),
('call center klikcair', 'call center'),
('nomor telepon klikcair', 'call center'),
('call center uang teman', 'call center'),
('nomor telepon uang teman', 'call center'),
('call center profindo', 'call center'),
('nomor telepon profindo', 'call center'),
('call center sophia mart', 'call center'),
('nomor telepon sophia mart', 'call center'),
('call center parental', 'call center'),
('nomor telepon parental', 'call center'),
('call center zensearch', 'call center'),
('nomor telepon zensearch', 'call center'),
('call center pinjol', 'call center'),
('nomor call center pinjol', 'call center'),
('call center easycash hubungi', 'call center'),
('cara keluar dari pinjol ilegal', 'pinjaman online'),
('cara melaporkan pinjol ilegal', 'pinjaman online'),
('pinjaman online terdaftar ojk', 'pinjaman online'),
('pinjol ilegal menagih ke keluarga', 'pinjaman online'),
('cara stop penagihan pinjol', 'pinjaman online'),
('call center ojk', 'call center'),
('nomor ojk untuk laporan pinjol', 'pinjaman online'),
('satgas pinjol ilegal', 'pinjaman online'),
('daftar pinjol resmi ojk', 'pinjaman online'),
('pinjaman online cepat cair 24 jam', 'pinjaman online'),
('pinjaman online tanpa bi checking', 'pinjaman online'),
('pinjaman online bagi pelanggan baru', 'pinjaman online'),
('pinjaman online cair 5 menit', 'pinjaman online'),
('pinjaman online bunga rendah', 'pinjaman online'),
('pinjaman online tanpa jaminan', 'pinjaman online'),
('pinjaman online sloncat', 'pinjaman online'),
('kredit online tanpa agunan', 'pinjaman online'),
('pinjaman online legal terbaik', 'pinjaman online'),
('rekomendasi pinjaman online aman', 'pinjaman online'),
('pinjaman online bunga 0 persen', 'pinjaman online'),
('pinjaman karyawan tanpa slip gaji', 'pinjaman online'),
('kta tanpa bpjs', 'pinjaman online'),
('forum keuangan', 'keuangan'),
('forum pinjaman online', 'pinjaman online'),
('diskusi investasi pemula', 'investasi'),
('investasi', 'investasi'),
('investasi saham untuk pemula', 'investasi'),
('cara beli saham pertama kali', 'investasi'),
('reksadana untuk pemula', 'investasi'),
('reksadana pendapatan tetap terbaik', 'investasi'),
('emas antisipasi inflasi', 'investasi'),
('deposito bank digital terbaik', 'investasi'),
('fintech', 'fintech'),
('ojk', 'regulasi'),
('regulasi fintech terbaru', 'regulasi'),
('saham bank blue chip', 'investasi'),
('cara daftar npwp online', 'regulasi'),
('buat npwp online gratis', 'regulasi'),
('pph tahunan lapor pajak', 'regulasi'),
('cara hitung pajak penghasilan', 'regulasi'),
('asuransi', 'asuransi'),
('asuransi kesehatan swasta vs bpjs', 'asuransi'),
('asuransi jiwa untuk keluarga muda', 'asuransi'),
('premi asuransi murah perlindungan besar', 'asuransi'),
('asuransi pendidikan anak', 'asuransi'),
('asuransi mobil all risk terbaik', 'asuransi'),
('asuransi perjalanan murah', 'asuransi'),
('bank digital', 'perbankan'),
('buka rekening bank digital', 'perbankan'),
('bank digital terbaik indonesia', 'perbankan'),
('saldo minimal bank digital', 'perbankan'),
('e-wallet', 'perbankan'),
('e-wallet terbaik indonesia', 'perbankan'),
('top up gratis ongkir dompet digital', 'perbankan'),
('cara cek skor kredit bik', 'pinjaman online'),
('bi checking bisa hapus sendiri', 'pinjaman online'),
('riwayat kredit macet solusi', 'pinjaman online'),
('kredit macet di bank bisa dihapus', 'pinjaman online'),
('restrukturisasi kredit', 'pinjaman online'),
('negosiasi cicilan kartu kredit', 'pinjaman online'),
('kartu kredit tanpa biaya tahunan', 'pinjaman online'),
('transfer antar bank tanpa biaya', 'perbankan'),
('kode bank semua bank di indonesia', 'perbankan'),
('pinjaman usaha mikro tanpa jaminan', 'pinjaman online'),
('kredit usaha rakyat murah', 'pinjaman online'),
('modal usaha kecil', 'pinjaman online'),
('saku darurat berapa gaji', 'keuangan'),
('atur keuangan gaji kecil', 'keuangan'),
('cara menabung cepat', 'keuangan'),
('menabung otomatis aplikasi', 'keuangan'),
('aplikasi pencatat keuangan', 'keuangan'),
('anggaran bulanan keluarga', 'keuangan'),
('keuangan rumah tangga miskin', 'keuangan'),
('cara melunasi hutang kartu kredit', 'pinjaman online'),
('konsolidasi pinjaman online', 'pinjaman online'),
('utang menumpuk apa solusi', 'pinjaman online'),
('dlc community pinjaman', 'pinjaman online'),
('kominfo laporkan pinjol', 'pinjaman online'),
('sikka ojk cek pinjol', 'pinjaman online'),
('cek lisensi pinjol di ojk', 'pinjaman online'),
('pinjol yang tidak menagih ke kontak', 'pinjaman online'),
('pinjol tanpa akses kontak', 'pinjaman online'),
('pinjol legal tanpa kontak darurat', 'pinjaman online'),
('pinjaman online tanpa verifikasi kontak', 'pinjaman online'),
('pinjol bayar nasabah hutang', 'pinjaman online'),
('cara agar pinjol tidak menghubungi kontak', 'call center'),
('data pribadi disalahgunakan pinjol', 'pinjaman online'),
('pinjol menyebar data pribadi ke sosial media', 'pinjaman online'),
('pinjol mengancam sebar ke wa kantor', 'pinjaman online'),
('lapor ke polisi pinjol menodong', 'pinjaman online'),
('paylater', 'pinjaman online'),
('paylater terbaik', 'pinjaman online'),
('paylater tanpa bunga', 'pinjaman online'),
('cicilan tanpa kartu kredit', 'pinjaman online'),
('belanja online cicilan 0 persen', 'pinjaman online'),
('kredivo limit menurun kenapa', 'pinjaman online'),
('akulaku bayar nanti', 'pinjaman online'),
('call center paylater', 'call center'),
('buy now pay later indonesia', 'umum'),
('pinjaman berbasis data', 'pinjaman online'),
('dana tunai tanpa jaminan', 'pinjaman online'),
('pinjaman tunai cepat', 'pinjaman online'),
('tarik tunai kartu kredit murah', 'pinjaman online'),
('tarik tunai pinjol', 'pinjaman online'),
('pinjaman jaminan bpkb', 'pinjaman online'),
('pinjaman jaminan sertifikat rumah', 'pinjaman online'),
('gadai emas di pegadaian', 'pinjaman online'),
('pegadaian call center', 'call center'),
('kta pegadaian', 'pinjaman online'),
('pinjaman koperasi simpan pinjam', 'pinjaman online'),
('koperasi pinjaman online legal', 'pinjaman online'),
('pinjaman dana desa', 'pinjaman online'),
('bank bpr kredit mikro', 'pinjaman online'),
('pinjaman bank bri untuk umkm', 'pinjaman online'),
('kredit mikro bank mandiri', 'pinjaman online'),
('pinjaman tanpa riba', 'pinjaman online'),
('kredit syariah tanpa riba', 'pinjaman online'),
('pembiayaan syariah ojk', 'regulasi'),
('cicilan halal tanpa riba', 'pinjaman online'),
('kartu kredit syariah', 'pinjaman online'),
('call center bank bca', 'call center'),
('call center bank mandiri', 'call center'),
('call center bank bri', 'call center'),
('call center bank bni', 'call center'),
('call center bank cimb niaga', 'call center'),
('call center bank permata', 'call center'),
('call center bank panin', 'call center'),
('call center bri agro', 'call center'),
('call center btpn jenius', 'call center'),
('call center bank syariah indonesia', 'call center'),
('call center btn', 'call center'),
('call center bank danamon', 'call center'),
('call center bank maybank', 'call center'),
('call center bank ocbc nisp', 'call center'),
('call center bank uob', 'call center'),
('call center bank dbss', 'call center'),
('call center bank standard chartered', 'call center'),
('call center bank hsbc', 'call center'),
('call center bank commonwealth', 'call center'),
('call center bank amar', 'call center'),
('call center bank seabank', 'call center'),
('call center bank neo commerce', 'call center'),
('call center bank index selindo', 'call center'),
('call center bank kebon jahe', 'call center'),
('call center tanya sanksi ojk', 'call center'),
('birokrasi keuangan indonesia', 'regulasi'),
('direktorat jenderal pengelolaan keuangan', 'keuangan');
